-- Aroma Ceylon Business App V2
-- Shops / Customers module
-- Run once in Supabase Dashboard > SQL Editor.

begin;

create table if not exists public.shops (
  id uuid primary key default gen_random_uuid(),
  shop_number bigint generated by default as identity unique,
  shop_code text generated always as (
    'SHOP-' || lpad(shop_number::text, 4, '0')
  ) stored unique,
  shop_name text not null,
  contact_person text,
  phone text,
  email text,
  address_line_1 text,
  address_line_2 text,
  city text,
  postal_code text,
  country text not null default 'Italy',
  vat_number text,
  payment_terms text not null default '30 days'
    check (payment_terms in ('Cash', '7 days', '15 days', '30 days')),
  default_currency text not null default 'EUR'
    check (default_currency in ('EUR', 'LKR')),
  notes text,
  active boolean not null default true,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists shops_name_idx
  on public.shops (lower(shop_name));
create index if not exists shops_active_idx
  on public.shops (active);
create index if not exists shops_city_idx
  on public.shops (lower(city));

drop trigger if exists shops_set_updated_at on public.shops;
create trigger shops_set_updated_at
before update on public.shops
for each row execute function public.set_updated_at();

drop trigger if exists audit_shops on public.shops;
create trigger audit_shops
after insert or update or delete on public.shops
for each row execute function public.write_audit_log();

alter table public.shops enable row level security;

drop policy if exists "shops_admin_all" on public.shops;
create policy "shops_admin_all"
on public.shops
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

grant select, insert, update, delete on public.shops to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
