-- Aroma Ceylon Business App V2
-- Sales, deliveries, invoices, payments and private PDF storage
-- Run once in Supabase Dashboard > SQL Editor.

begin;

do $$
begin
  create type public.sales_invoice_status as enum (
    'draft',
    'sent',
    'partially_paid',
    'paid',
    'overdue',
    'cancelled'
  );
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.sales_delivery_status as enum (
    'pending',
    'packed',
    'delivered',
    'cancelled'
  );
exception
  when duplicate_object then null;
end $$;

create table if not exists public.sales_invoices (
  id uuid primary key default gen_random_uuid(),
  invoice_number bigint generated by default as identity unique,
  invoice_code text generated always as (
    'INV-' || lpad(invoice_number::text, 6, '0')
  ) stored unique,
  shop_id uuid not null references public.shops(id) on delete restrict,
  invoice_date date not null default current_date,
  due_date date not null default current_date,
  delivery_date date,
  currency text not null default 'EUR' check (currency in ('EUR', 'LKR')),
  subtotal numeric(14,2) not null default 0 check (subtotal >= 0),
  discount_amount numeric(14,2) not null default 0 check (discount_amount >= 0),
  tax_rate numeric(6,3) not null default 0 check (tax_rate >= 0 and tax_rate <= 100),
  tax_amount numeric(14,2) not null default 0 check (tax_amount >= 0),
  total_amount numeric(14,2) not null default 0 check (total_amount >= 0),
  paid_amount numeric(14,2) not null default 0 check (paid_amount >= 0),
  balance_amount numeric(14,2) not null default 0 check (balance_amount >= 0),
  status public.sales_invoice_status not null default 'draft',
  delivery_status public.sales_delivery_status not null default 'pending',
  notes text,
  invoice_pdf_path text,
  delivery_pdf_path text,
  created_by uuid not null references public.profiles(id) on delete restrict,
  sent_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (due_date >= invoice_date),
  check (delivery_date is null or delivery_date >= invoice_date),
  check (discount_amount <= subtotal),
  check (paid_amount <= total_amount + 0.01),
  check (balance_amount <= total_amount + 0.01)
);

create table if not exists public.sales_invoice_items (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.sales_invoices(id) on delete cascade,
  product_id uuid references public.products(id) on delete restrict,
  product_name text not null,
  sku text not null,
  pack_size text,
  quantity numeric(12,3) not null check (quantity > 0),
  unit_price numeric(14,2) not null check (unit_price >= 0),
  line_total numeric(14,2) not null check (line_total >= 0),
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.sales_invoice_payments (
  id uuid primary key default gen_random_uuid(),
  invoice_id uuid not null references public.sales_invoices(id) on delete cascade,
  payment_date date not null default current_date,
  amount numeric(14,2) not null check (amount > 0),
  payment_method text not null default 'Bank transfer'
    check (payment_method in ('Cash', 'Bank transfer', 'Card', 'Other')),
  reference text,
  notes text,
  created_by uuid not null references public.profiles(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists sales_invoices_shop_date_idx
  on public.sales_invoices (shop_id, invoice_date desc);
create index if not exists sales_invoices_status_due_idx
  on public.sales_invoices (status, due_date);
create index if not exists sales_invoice_items_invoice_idx
  on public.sales_invoice_items (invoice_id, sort_order);
create index if not exists sales_invoice_payments_invoice_idx
  on public.sales_invoice_payments (invoice_id, payment_date desc);

drop trigger if exists sales_invoices_set_updated_at on public.sales_invoices;
create trigger sales_invoices_set_updated_at
before update on public.sales_invoices
for each row execute function public.set_updated_at();

drop trigger if exists audit_sales_invoices on public.sales_invoices;
create trigger audit_sales_invoices
after insert or update or delete on public.sales_invoices
for each row execute function public.write_audit_log();

drop trigger if exists audit_sales_invoice_items on public.sales_invoice_items;
create trigger audit_sales_invoice_items
after insert or update or delete on public.sales_invoice_items
for each row execute function public.write_audit_log();

drop trigger if exists audit_sales_invoice_payments on public.sales_invoice_payments;
create trigger audit_sales_invoice_payments
after insert or update or delete on public.sales_invoice_payments
for each row execute function public.write_audit_log();

alter table public.sales_invoices enable row level security;
alter table public.sales_invoice_items enable row level security;
alter table public.sales_invoice_payments enable row level security;

drop policy if exists "sales_invoices_admin_all" on public.sales_invoices;
create policy "sales_invoices_admin_all"
on public.sales_invoices
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "sales_invoice_items_admin_all" on public.sales_invoice_items;
create policy "sales_invoice_items_admin_all"
on public.sales_invoice_items
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

drop policy if exists "sales_invoice_payments_admin_all" on public.sales_invoice_payments;
create policy "sales_invoice_payments_admin_all"
on public.sales_invoice_payments
for all
to authenticated
using ((select public.is_admin()))
with check ((select public.is_admin()));

create or replace function public.save_sales_invoice(
  p_invoice_id uuid,
  p_shop_id uuid,
  p_invoice_date date,
  p_due_date date,
  p_delivery_date date,
  p_currency text,
  p_discount_amount numeric,
  p_tax_rate numeric,
  p_notes text,
  p_items jsonb
)
returns uuid
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_invoice_id uuid;
  v_current_status public.sales_invoice_status;
  v_item jsonb;
  v_product_id uuid;
  v_product_name text;
  v_sku text;
  v_pack_size text;
  v_product_currency text;
  v_quantity numeric(12,3);
  v_unit_price numeric(14,2);
  v_line_total numeric(14,2);
  v_subtotal numeric(14,2) := 0;
  v_discount numeric(14,2) := round(greatest(coalesce(p_discount_amount, 0), 0), 2);
  v_tax_rate numeric(6,3) := round(greatest(coalesce(p_tax_rate, 0), 0), 3);
  v_taxable numeric(14,2);
  v_tax_amount numeric(14,2);
  v_total numeric(14,2);
  v_sort integer := 0;
begin
  if not public.is_admin() then
    raise exception 'Administrator access is required.';
  end if;

  if p_shop_id is null or not exists (
    select 1 from public.shops where id = p_shop_id and active = true
  ) then
    raise exception 'Select an active shop.';
  end if;

  if p_invoice_date is null or p_due_date is null or p_due_date < p_invoice_date then
    raise exception 'The due date must be on or after the invoice date.';
  end if;

  if p_delivery_date is not null and p_delivery_date < p_invoice_date then
    raise exception 'The delivery date must be on or after the invoice date.';
  end if;

  if p_currency not in ('EUR', 'LKR') then
    raise exception 'Unsupported invoice currency.';
  end if;

  if v_tax_rate > 100 then
    raise exception 'Tax rate cannot be greater than 100 percent.';
  end if;

  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Add at least one product.';
  end if;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := nullif(v_item->>'product_id', '')::uuid;
    v_quantity := round(coalesce(nullif(v_item->>'quantity', '')::numeric, 0), 3);
    v_unit_price := round(coalesce(nullif(v_item->>'unit_price', '')::numeric, 0), 2);

    if v_product_id is null then
      raise exception 'Every line must have a product.';
    end if;

    select name, sku, pack_size, currency
      into v_product_name, v_sku, v_pack_size, v_product_currency
    from public.products
    where id = v_product_id;

    if not found then
      raise exception 'A selected product no longer exists.';
    end if;

    if v_product_currency <> p_currency then
      raise exception 'All products must use the invoice currency.';
    end if;

    if v_quantity <= 0 then
      raise exception 'Product quantity must be greater than zero.';
    end if;

    if v_unit_price < 0 then
      raise exception 'Unit price cannot be negative.';
    end if;

    v_line_total := round(v_quantity * v_unit_price, 2);
    v_subtotal := v_subtotal + v_line_total;
  end loop;

  v_subtotal := round(v_subtotal, 2);
  if v_discount > v_subtotal then
    raise exception 'Discount cannot be greater than the subtotal.';
  end if;

  v_taxable := round(v_subtotal - v_discount, 2);
  v_tax_amount := round(v_taxable * v_tax_rate / 100, 2);
  v_total := round(v_taxable + v_tax_amount, 2);

  if p_invoice_id is null then
    insert into public.sales_invoices (
      shop_id,
      invoice_date,
      due_date,
      delivery_date,
      currency,
      subtotal,
      discount_amount,
      tax_rate,
      tax_amount,
      total_amount,
      paid_amount,
      balance_amount,
      status,
      delivery_status,
      notes,
      created_by
    )
    values (
      p_shop_id,
      p_invoice_date,
      p_due_date,
      p_delivery_date,
      p_currency,
      v_subtotal,
      v_discount,
      v_tax_rate,
      v_tax_amount,
      v_total,
      0,
      v_total,
      'draft',
      'pending',
      nullif(trim(coalesce(p_notes, '')), ''),
      auth.uid()
    )
    returning id into v_invoice_id;
  else
    select status into v_current_status
    from public.sales_invoices
    where id = p_invoice_id
    for update;

    if not found then
      raise exception 'Invoice not found.';
    end if;

    if v_current_status <> 'draft' then
      raise exception 'Only draft invoices can be edited.';
    end if;

    update public.sales_invoices
    set shop_id = p_shop_id,
        invoice_date = p_invoice_date,
        due_date = p_due_date,
        delivery_date = p_delivery_date,
        currency = p_currency,
        subtotal = v_subtotal,
        discount_amount = v_discount,
        tax_rate = v_tax_rate,
        tax_amount = v_tax_amount,
        total_amount = v_total,
        paid_amount = 0,
        balance_amount = v_total,
        notes = nullif(trim(coalesce(p_notes, '')), '')
    where id = p_invoice_id;

    delete from public.sales_invoice_items where invoice_id = p_invoice_id;
    v_invoice_id := p_invoice_id;
  end if;

  v_sort := 0;
  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_product_id := nullif(v_item->>'product_id', '')::uuid;
    v_quantity := round(coalesce(nullif(v_item->>'quantity', '')::numeric, 0), 3);
    v_unit_price := round(coalesce(nullif(v_item->>'unit_price', '')::numeric, 0), 2);

    select name, sku, pack_size
      into v_product_name, v_sku, v_pack_size
    from public.products
    where id = v_product_id;

    v_line_total := round(v_quantity * v_unit_price, 2);

    insert into public.sales_invoice_items (
      invoice_id,
      product_id,
      product_name,
      sku,
      pack_size,
      quantity,
      unit_price,
      line_total,
      sort_order
    )
    values (
      v_invoice_id,
      v_product_id,
      v_product_name,
      v_sku,
      v_pack_size,
      v_quantity,
      v_unit_price,
      v_line_total,
      v_sort
    );

    v_sort := v_sort + 1;
  end loop;

  return v_invoice_id;
end;
$$;

create or replace function public.validate_sales_invoice_payment()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_total numeric(14,2);
  v_paid numeric(14,2);
  v_status public.sales_invoice_status;
  v_existing numeric(14,2) := 0;
begin
  if not public.is_admin() then
    raise exception 'Administrator access is required.';
  end if;

  select total_amount, paid_amount, status
    into v_total, v_paid, v_status
  from public.sales_invoices
  where id = new.invoice_id
  for update;

  if not found then
    raise exception 'Invoice not found.';
  end if;

  if v_status in ('draft', 'cancelled') then
    raise exception 'Payments cannot be added to this invoice.';
  end if;

  if tg_op = 'UPDATE' then
    v_existing := old.amount;
  end if;

  if new.amount <= 0 then
    raise exception 'Payment amount must be greater than zero.';
  end if;

  if (v_paid - v_existing + new.amount) > (v_total + 0.01) then
    raise exception 'Payment is greater than the outstanding balance.';
  end if;

  return new;
end;
$$;

create or replace function public.recalculate_sales_invoice_after_payment()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_invoice_id uuid;
  v_paid numeric(14,2);
  v_total numeric(14,2);
  v_due date;
  v_current public.sales_invoice_status;
  v_status public.sales_invoice_status;
begin
  if tg_op = 'DELETE' then
    v_invoice_id := old.invoice_id;
  else
    v_invoice_id := new.invoice_id;
  end if;

  select total_amount, due_date, status
    into v_total, v_due, v_current
  from public.sales_invoices
  where id = v_invoice_id
  for update;

  select coalesce(sum(amount), 0)
    into v_paid
  from public.sales_invoice_payments
  where invoice_id = v_invoice_id;

  v_paid := round(v_paid, 2);

  if v_current = 'cancelled' then
    v_status := 'cancelled';
  elsif v_paid >= v_total - 0.01 then
    v_status := 'paid';
  elsif v_due < current_date then
    v_status := 'overdue';
  elsif v_paid > 0 then
    v_status := 'partially_paid';
  else
    v_status := 'sent';
  end if;

  update public.sales_invoices
  set paid_amount = v_paid,
      balance_amount = greatest(round(v_total - v_paid, 2), 0),
      status = v_status
  where id = v_invoice_id;

  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

drop trigger if exists sales_invoice_payment_validate on public.sales_invoice_payments;
create trigger sales_invoice_payment_validate
before insert or update on public.sales_invoice_payments
for each row execute function public.validate_sales_invoice_payment();

drop trigger if exists sales_invoice_payment_recalculate on public.sales_invoice_payments;
create trigger sales_invoice_payment_recalculate
after insert or update or delete on public.sales_invoice_payments
for each row execute function public.recalculate_sales_invoice_after_payment();

create or replace function public.refresh_sales_invoice_statuses()
returns integer
language plpgsql
security invoker
set search_path = public
as $$
declare
  v_count integer := 0;
begin
  if not public.is_admin() then
    raise exception 'Administrator access is required.';
  end if;

  update public.sales_invoices
  set status = case
    when paid_amount >= total_amount - 0.01 then 'paid'::public.sales_invoice_status
    when due_date < current_date and balance_amount > 0 then 'overdue'::public.sales_invoice_status
    when paid_amount > 0 then 'partially_paid'::public.sales_invoice_status
    else 'sent'::public.sales_invoice_status
  end
  where status not in ('draft', 'cancelled')
    and status is distinct from case
      when paid_amount >= total_amount - 0.01 then 'paid'::public.sales_invoice_status
      when due_date < current_date and balance_amount > 0 then 'overdue'::public.sales_invoice_status
      when paid_amount > 0 then 'partially_paid'::public.sales_invoice_status
      else 'sent'::public.sales_invoice_status
    end;

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

grant select, insert, update, delete on public.sales_invoices to authenticated;
grant select, insert, update, delete on public.sales_invoice_items to authenticated;
grant select, insert, update, delete on public.sales_invoice_payments to authenticated;
grant usage, select on all sequences in schema public to authenticated;
grant execute on function public.save_sales_invoice(uuid, uuid, date, date, date, text, numeric, numeric, text, jsonb) to authenticated;
grant execute on function public.refresh_sales_invoice_statuses() to authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'sales-documents',
  'sales-documents',
  false,
  10485760,
  array['application/pdf']
)
on conflict (id) do update set
  public = false,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists "sales_documents_admin_select" on storage.objects;
create policy "sales_documents_admin_select"
on storage.objects
for select
to authenticated
using (
  bucket_id = 'sales-documents'
  and (select public.is_admin())
);

drop policy if exists "sales_documents_admin_insert" on storage.objects;
create policy "sales_documents_admin_insert"
on storage.objects
for insert
to authenticated
with check (
  bucket_id = 'sales-documents'
  and (select public.is_admin())
);

drop policy if exists "sales_documents_admin_update" on storage.objects;
create policy "sales_documents_admin_update"
on storage.objects
for update
to authenticated
using (
  bucket_id = 'sales-documents'
  and (select public.is_admin())
)
with check (
  bucket_id = 'sales-documents'
  and (select public.is_admin())
);

drop policy if exists "sales_documents_admin_delete" on storage.objects;
create policy "sales_documents_admin_delete"
on storage.objects
for delete
to authenticated
using (
  bucket_id = 'sales-documents'
  and (select public.is_admin())
);

commit;
